<?php
// $Id:

/**
 * @file
 * Site-wide contact form in block.
 * @author Vikom (drupal.org/user/279158)
 */

/**
 * Implements hook_block_info().
 */
function contactblock_block_info() {
  $blocks['contactblock'] = array(
    'info' => t('Contact block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function contactblock_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'contactblock':
      return array(
        'subject' => t('Contact'),
        'content' => contactblock_get_contact_form(),
      );
      break;

  }
  return $block;
}

function contactblock_get_contact_form() {
	global $user;
  form_load_include($form_state, 'inc', 'contact', 'contact.pages');

  $form = drupal_get_form('contact_site_form');
   $form['name']['#value'] = $user->uid ? format_username($user) : 'Your Name';
   $form['name']['#attributes'] = array('this.value = "Your Name"','onblur' => "if (this.value == '') {this.value = '".'Your Name'."';}", 'onfocus' => "if (this.value == '".'Your Name'."') {this.value = '';}");
   $form['mail']['#value'] = $user->uid ? $user->mail : 'Your Email';
   $form['mail']['#attributes'] = array('onblur' => "if (this.value == '') {this.value = '".'Your Email'."';}", 'onfocus' => "if (this.value == '".'Your Email'."') {this.value = '';}");
   $form['subject']['#value'] = 'Subject';
   $form['subject']['#attributes'] = array('onblur' => "if (this.value == '') {this.value = '".'Subject'."';}", 'onfocus' => "if (this.value == '".'Subject'."') {this.value = '';}");
   $form['message']['#value'] = 'Message';
   $form['message']['#attributes'] = array('onblur' => "if (this.value == '') {this.value = '".'Message'."';}", 'onfocus' => "if (this.value == '".'Message'."') {this.value = '';}");
   $form['actions']['submit']['#value'] = 'SUBMIT';

  $output1 = drupal_render($form);
	$output = '<div id = "contactblock">'.$output1.'</div>';
  return $output;
}



